# permissions for end users to view overlays.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: overlay-viewer-role
rules:
- apiGroups:
  - kontinuum-controller.kontinuum-controller.github.io
  resources:
  - overlays
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kontinuum-controller.kontinuum-controller.github.io
  resources:
  - overlays/status
  verbs:
  - get
