# permissions for end users to edit overlays.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: overlay-editor-role
rules:
- apiGroups:
  - kontinuum-controller.kontinuum-controller.github.io
  resources:
  - overlays
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kontinuum-controller.kontinuum-controller.github.io
  resources:
  - overlays/status
  verbs:
  - get
