# permissions for end users to view targets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: target-viewer-role
rules:
- apiGroups:
  - kontinuum-controller.kontinuum-controller.github.io
  resources:
  - targets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kontinuum-controller.kontinuum-controller.github.io
  resources:
  - targets/status
  verbs:
  - get
