# permissions for end users to view workloads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workload-viewer-role
rules:
- apiGroups:
  - crd.kontinuum-controller.github.io
  resources:
  - workloads
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crd.kontinuum-controller.github.io
  resources:
  - workloads/status
  verbs:
  - get
