apiVersion: crd.kontinuum-controller.github.io/v1alpha1
kind: Target
metadata:
  name: edge
  labels:
    arch: x86
    group: edge
    name: edge
spec:
  s3:
    credentialSecretName: s3-secret
    bucketName:  kontinuum-controller
    folder: edge
    provider: AWS
    endpoint: fra1.digitaloceanspaces.com
