apiVersion: crd.kontinuum-controller.github.io/v1alpha1
kind: Workload
metadata:
  name: nginx-workload
spec:
  selector:
    matchLabels:
      arch: x86
  components:
  - name: nginx-sample
    type: nginx
    values:
      service:
        type: ClusterIP
  managedComponents: []
